### ISSUE TITLE
Asian points

### ISSUE THREAD

**Issue by RussianSpy** [rapideditor/country-coder#142]
This package has issues with Asian points. I tried to use it for my personal educational project, but unfortunetly for 80% of coordinates it returned null.
Here is the list of some "null" points:
1) 13.74739497, 100.540694
2) 12.9294389, 100.880471
3)  14.3427277, 100.5417638
4)  22.19230472, 113.540945
5) 13.412475, 103.8604716
6)  17.9672858, 102.6166749

At the same time other photos taken in Europe by the same camera are fine.

**Comment by bhousel** [comment]
You might be mixing up the coordinates?  This package expects them in `longitude, latitude` order.
